@startuml
skinparam svgDimensionStyle true

interface DiagnosticReport {
    identifier;
    basedOn;
    category=#LAB;
    code.text=`CH`;
    subject;
    effectiveDateTime;
    issued;
    performer;
    specimen;
    results;
    extension[notes];
}
class ServiceRequest {
    status=#unknown;
    intent=#order;
    category;
    code;
    subject;
    requester;
    performer;
}
class Specimen {
    status;
    type;
    request;
    collection.collectionDateTime;
}
class Observation {
    basedOn;
    status;
    category=#laboratory;
    code;
    subject;
    effectiveDateTime;
    issued;
    performer;
    value[x];
    interpretation;
    note;
    specimen;
    referenceRange;
}

DiagnosticReport -down-> Specimen: 1..1 specimen
Specimen -right-> ServiceRequest: 1..1 request
DiagnosticReport -right-> ServiceRequest: 1..* basedOn
Observation -up-> ServiceRequest: 1..1 basedOn
DiagnosticReport -down-> Observation: 0..* results
Observation -right-> Specimen: 1..1 specimen

@enduml