@startuml
skinparam svgDimensionStyle false

package source {
    class source.HDR
    class source.VIA
    class source.HL7v2
}

package fhir {
    package util {
        class fhir.util.Patient {
MHV Patient 
             }
        class fhir.util.Practitioner
        class fhir.util.Location
        class fhir.util.Organization
    }
    class fhir.AllergyIntolerance
    class fhir.Immunization
    class fhir.Condition
    class fhir.DiagnosticReport {
        - VIA
        -- lab
        - HDR
        -- chem 
        -- hem 
        Specimen()
        Observation()
    }
    class fhir.DocumentReference {
        - Progress Note 
        - Discharge Summary
        - ECG Report
        - Imaging Report
    }
    class fhir.Observation {
        - BLOOD PRESSURE 
        - HEIGHT
        - WEIGHT
        - PULSE 
        - PAIN 
        - RESPIRATION 
        - TEMPERATURE 
    }
    class fhir.MedicationRequest
    class fhir.MedicationDispense
}

source.HL7v2 -[#blue]down-> fhir.MedicationRequest
source.HL7v2 -[#blue]down-> fhir.MedicationDispense
source.HL7v2 ..[#blue]down. fhir.util.Patient

source.VIA ..[#red]down. fhir.util.Patient
source.VIA -[#red]down-> fhir.util.Practitioner
source.VIA -[#red]down-> fhir.util.Location
source.VIA -[#red]down-> fhir.util.Organization
source.VIA -[#red]down-> fhir.Observation
source.VIA -[#red]down-> fhir.DiagnosticReport

source.VIA -[#red]down-> fhir.Condition
source.VIA -[#red]down-> fhir.DocumentReference
source.VIA -[#red]down-> fhir.Immunization

source.HDR -[#green]down-> fhir.DiagnosticReport
source.HDR -[#green]down-> fhir.AllergyIntolerance

source.HDR ..[#green]down. fhir.util.Patient
source.HDR -[#green]down-> fhir.util.Practitioner
source.HDR -[#green]down-> fhir.util.Location
source.HDR -[#green]down-> fhir.util.Organization

interface "FHIR API" as API 
API -up-> fhir

@enduml